MODEL:
  TYPE: resnet
  NAME: tv_resnet50
  DROP_PATH_RATE: 0.5
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
TRAIN:
  BASE_LR: 5e-4
HASH:
  HASH_BIT: 64
  GAMMA: 20.0
  LAMBD: 0.1
  LAMBD_CLS: 0.1
DATA:
  DATASET: Dogs
