MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window7_224
  DROP_PATH_RATE: 0.5
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
TRAIN:
  BASE_LR: 5e-4
HASH:
  GAMMA: 20.0
  HASH_BIT: 32
  LAMBD: 0.1
  LAMBD_CLS: 0.1
  PRETRAINED: downloads/swin_base_patch4_window7_224_22k.pth
