MODEL:
  TYPE: swin_gwl
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
  ATT_SIZE: 4
TRAIN:
  BASE_LR: 5e-4
HASH:
  GAMMA: 20.0
  HASH_BIT: 32
  LAMBD: 0.1
  LAMBD_CLS: 0.1
  LAMBD_SP: 0.1
  LAMBD_CH: 0.1
  PRETRAINED: downloads/swin_tiny_patch4_window7_224.pth
